# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install -g yo
  displayName: 'Global dependencies'

- script: |
    npm install
    npm run build
  displayName: 'Dependencies & Build'

- script: npm run test
  displayName: 'Run tests'